const Asena = require('../events');
const {MessageType,Mimetype} = require('@adiwajshing/baileys');
const fs = require('fs');
const ffmpeg = require('fluent-ffmpeg');
const {execFile} = require('child_process');
const cwebp = require('cwebp-bin');
const Config = require('../config');

const Language = require('../language');
const Lang = Language.getString('cmdlist');

if (Config.WORKTYPE == 'private') {

Asena.addCommand({pattern: 'jcmd', fromMe: true, deleteCommand: false, desc: Lang.JCMD_DESC}, (async (message, match) => {


        await message.sendMessage('●▬*𝓙𝓮𝓼𝓼𝓲𝓮 𝙲𝚘𝚖𝚖𝚊𝚗𝚍-𝙻𝚒𝚜𝚝*☯▬●\n\n🎯 Command: *.yt*\n📝 Description:```It searches on YouTube.```\n\n🎯 Command: *.song Enter_Your_Song_Name*\n📝 Description:```Uploads the song you wrote.```\n\n🎯 Command: *.song YoutubeVideo_Link*\n📝 Description:```Download Youtube  video to mp3.```\n\n🎯 Command: *.video YoutubeVideo_Link*\n📝 Description:```Downloads video from YouTube.\n⚠️( Please Less than 30 minutes in your youtube video)```\n\n🎯 Command: *.mp4audio*\n📝 Description:```It converts video to sound.```\n\n🎯 Command: *.tts*\n📝 Description:```It converts text to sound.```\n\n🎯 Command: *.sticker*\n📝 Description:```It converts your replied photo to a sticker. Put a sticker and mention sticker and type command.```\n\n🎯 Command: *.attp*\n📝 Description:```Adds rainbow effect to the text as a sticker.```\n\n🎯 Command: *.imagesticker*\n📝 Description:```Converts the sticker to a photo. Put a sticker and mention sticker and type command.```\n\n🎯 Command: *.ttp*\n📝 Description:```Converts text to plain painting.```\n\n🎯 Command: *.glowttp*\n📝 Description:```Converts text to neon painting.```\n\n🎯 Command: *.removebg*\n📝 Description:```Removes the background of the photos.```\n\n🎯 Command: *.meme*\n📝 Description:```Photo memes you replied to.```\n\n🎯 Command: *.wallpaper*\n📝 Description:```It sends high resolution random wallpapers.```\n\n🎯 Command: *.bwimage*\n📝 Description:```Applies a black and white effect to image```\n\n🎯 Command: *.harrypotter*\n📝 Description:```Converts the text into harry potter image```\n\n🎯 Command: *.neonlight*\n📝 Description:```Converts the text into neon light image```\n\n🎯 Command: *.weather*\n📝 Description:```This shows the weather in your City.```*⌨️ Example:*.weather Colombo\n\n🎯 Command: *.ocr*\n📝 Description:```Reads the text on the photo you have replied to. It works English Languages Photo. Not Support Sinhala.```\n\n🎯 Command: *.blurimage*\n📝 Description:```Blurs the background of the photo.```\n\n🎯 Command: *.trt*\n📝 Description:```It translates with Google Translate. You must reply to any message.```\n*⌨️ Example:*.trt en si (From English to Sinhala)\n\n🎯 Command: *.ss*\n📝 Description:```Takes a screenshot from the page in the given link.```\n\n🎯 Command: *.quote*\n📝 Description:```It Sends Random Quote.```\n\n🎯 Command: *.ss*\n📝 Description:```Displays metadata data of group or person.```\n\n⭕ ```Can Use Only English Characters...!```\n\n⚠️ Warning!\n *Please, Do not Access to Use Private Use this bot* ❌\n*Using the bot out of purpose will explicitly ban you.*\n\n*𝓙𝓮𝓼𝓼𝓲𝓮 Bot Owner* - 𝚃𝚑𝚊𝚛𝚒𝚗𝚍𝚞 𝙳𝚑𝚊𝚗𝚞𝚜𝚑𝚔𝚊\n𝒞𝑜𝓃𝓉𝒶𝒸𝓉 𝓂𝑒 - wa.me/+94769183064');

    }));

}
else if (Config.WORKTYPE == 'public') {
Asena.addCommand({pattern: 'jcmd', fromMe: true, deleteCommand: false, desc: Lang.JCMD_DESC}, (async (message, match) => {


        await message.sendMessage('●▬*𝓙𝓮𝓼𝓼𝓲𝓮 𝙲𝚘𝚖𝚖𝚊𝚗𝚍-𝙻𝚒𝚜𝚝*☯▬●\n\n🎯 Command: *.yt*\n📝 Description:```It searches on YouTube.```\n\n🎯 Command: *.song Enter_Your_Song_Name*\n📝 Description:```Uploads the song you wrote.```\n\n🎯 Command: *.song YoutubeVideo_Link*\n📝 Description:```Download Youtube  video to mp3.```\n\n🎯 Command: *.video YoutubeVideo_Link*\n📝 Description:```Downloads video from YouTube.\n⚠️( Please Less than 30 minutes in your youtube video)```\n\n🎯 Command: *.mp4audio*\n📝 Description:```It converts video to sound.```\n\n🎯 Command: *.tts*\n📝 Description:```It converts text to sound.```\n\n🎯 Command: *.sticker*\n📝 Description:```It converts your replied photo to a sticker. Put a sticker and mention sticker and type command.```\n\n🎯 Command: *.attp*\n📝 Description:```Adds rainbow effect to the text as a sticker.```\n\n🎯 Command: *.imagesticker*\n📝 Description:```Converts the sticker to a photo. Put a sticker and mention sticker and type command.```\n\n🎯 Command: *.ttp*\n📝 Description:```Converts text to plain painting.```\n\n🎯 Command: *.glowttp*\n📝 Description:```Converts text to neon painting.```\n\n🎯 Command: *.removebg*\n📝 Description:```Removes the background of the photos.```\n\n🎯 Command: *.meme*\n📝 Description:```Photo memes you replied to.```\n\n🎯 Command: *.wallpaper*\n📝 Description:```It sends high resolution random wallpapers.```\n\n🎯 Command: *.bwimage*\n📝 Description:```Applies a black and white effect to image```\n\n🎯 Command: *.harrypotter*\n📝 Description:```Converts the text into harry potter image```\n\n🎯 Command: *.neonlight*\n📝 Description:```Converts the text into neon light image```\n\n🎯 Command: *.weather*\n📝 Description:```This shows the weather in your City.```*⌨️ Example:*.weather Colombo\n\n🎯 Command: *.ocr*\n📝 Description:```Reads the text on the photo you have replied to. It works English Languages Photo. Not Support Sinhala.```\n\n🎯 Command: *.blurimage*\n📝 Description:```Blurs the background of the photo.```\n\n🎯 Command: *.trt*\n📝 Description:```It translates with Google Translate. You must reply to any message.```\n*⌨️ Example:*.trt en si (From English to Sinhala)\n\n🎯 Command: *.ss*\n📝 Description:```Takes a screenshot from the page in the given link.```\n\n🎯 Command: *.quote*\n📝 Description:```It Sends Random Quote.```\n\n🎯 Command: *.ss*\n📝 Description:```Displays metadata data of group or person.```\n\n⭕ ```Can Use Only English Characters...!```\n\n⚠️ Warning!\n *Please, Do not Access to Use Private Use this bot* ❌\n*Using the bot out of purpose will explicitly ban you.*\n\n*𝓙𝓮𝓼𝓼𝓲𝓮 Bot Owner* - 𝚃𝚑𝚊𝚛𝚒𝚗𝚍𝚞 𝙳𝚑𝚊𝚗𝚞𝚜𝚑𝚔𝚊\n𝒞𝑜𝓃𝓉𝒶𝒸𝓉 𝓂𝑒 - wa.me/+94769183064');

    }));

}
